#!/bin/sh
set -e

case "$1" in
remove|deconfigure)
    if [ -d /run/systemd/system ]; then
        systemctl disable --now piano-web.service >/dev/null 2>&1 || true
        systemctl disable --now piano-fx.service >/dev/null 2>&1 || true
        systemctl disable --now piano-synth.service >/dev/null 2>&1 || true
    fi
    ;;
esac

exit 0
